DEFAULT_SYSTEM_PROMPT = """\
You are a transcript editor. Clean up the following interview transcript \
that was generated by automatic speech recognition (ASR).

Additional context: The speakers are Swiss German speakers. The ASR system \
transcribed into Standard German. Fix any garbled Swiss place names, \
institutions, or expressions that were misrecognized.

Your tasks:
1. Fix punctuation, capitalization, and sentence boundaries
2. Remove excessive filler words (um, uh, like, you know) but keep some for naturalness
3. Fix obvious ASR transcription errors and garbled words
4. Correct mangled proper nouns and technical terms where you can confidently infer the correct form
5. Light grammar cleanup where the meaning is clear

Rules:
- Preserve speaker labels EXACTLY as they appear (e.g., "Speaker 1:", "Speaker 2:")
- Preserve the original language — do NOT translate
- Preserve the original meaning — do NOT add, remove, or change the substance of what was said
- Preserve paragraph breaks between speaker turns
- Return ONLY the cleaned transcript, no commentary or explanations"""


def chunk_transcript(paragraphs, max_words=3000, overlap_turns=2):
    """Split paragraphs into chunks at speaker turn boundaries.

    Each chunk stays under max_words. Consecutive chunks share overlap_turns
    for context continuity.
    """
    chunks = []
    current_chunk = []
    current_words = 0

    for para in paragraphs:
        para_words = len(para.split())
        if current_words + para_words > max_words and current_chunk:
            chunks.append(current_chunk)
            current_chunk = current_chunk[-overlap_turns:] if overlap_turns > 0 else []
            current_words = sum(len(p.split()) for p in current_chunk)
        current_chunk.append(para)
        current_words += para_words

    if current_chunk:
        chunks.append(current_chunk)

    return chunks


def call_llm(text, provider, model, api_key, system_prompt):
    """Send text to LLM for cleanup. Returns cleaned text."""
    if provider == "anthropic":
        import anthropic

        client = anthropic.Anthropic(api_key=api_key)
        response = client.messages.create(
            model=model,
            max_tokens=8192,
            system=system_prompt,
            messages=[{"role": "user", "content": text}],
        )
        return response.content[0].text
    elif provider == "openai":
        import openai

        client = openai.OpenAI(api_key=api_key)
        response = client.responses.create(
            model=model,
            instructions=system_prompt,
            input=text,
        )
        return response.output_text
    else:
        raise ValueError(f"Unknown LLM provider: {provider}")


def postprocess_transcript(raw_paragraphs, cfg, llm_api_key):
    """Clean transcript using LLM. Returns final transcript string."""
    if not cfg.enable_llm_postprocessing or not llm_api_key:
        return "\n\n".join(raw_paragraphs)

    system_prompt = cfg.llm_system_prompt or DEFAULT_SYSTEM_PROMPT
    llm_model = cfg.get_llm_model()
    print(f"LLM post-processing with {cfg.llm_provider} / {llm_model}")

    chunks = chunk_transcript(raw_paragraphs)
    print(f"Split transcript into {len(chunks)} chunk(s)")
    for i, chunk in enumerate(chunks):
        word_count = sum(len(p.split()) for p in chunk)
        print(f"  Chunk {i+1}: {len(chunk)} turns, ~{word_count} words")

    cleaned_parts = []
    for i, chunk in enumerate(chunks):
        chunk_text = "\n\n".join(chunk)
        print(f"  Processing chunk {i+1}/{len(chunks)}...")
        cleaned = call_llm(chunk_text, cfg.llm_provider, llm_model, llm_api_key, system_prompt)
        cleaned_parts.append(cleaned)

    # Merge chunks, removing overlap duplicates
    final = cleaned_parts[0]
    for part in cleaned_parts[1:]:
        lines = part.strip().split("\n\n")
        new_lines = lines[2:]  # skip overlap_turns=2
        if new_lines:
            final += "\n\n" + "\n\n".join(new_lines)

    print(f"Done. Cleaned transcript: {len(final)} chars")
    return final
